version: "3.9"

services:
  server_blue:
    build:
      context: ./server
      args:
        APP_VERSION: "blue-v1"
    container_name: server_blue
    expose:
      - "5000"

  server_green:
    build:
      context: ./server
      args:
        APP_VERSION : "green-v1"
    container_name: server_green
    expose:
      - "5000"

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "5000:80"
    depends_on:
      - server_blue
      - server_green

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: client_app
    ports:
      - "3000:3000"
    depends_on:
      - nginx
