global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself so you can test prometheus_http_requests_total
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # CI/CD DORA Metrics Pushgateway
  - job_name: "pushgateway"
    static_configs:
      - targets: ["localhost:9091", "pushgateway:9091"]
