global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself so you can test prometheus_http_requests_total
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape cAdvisor for CPU, RAM, and Network metrics of all containers
  - job_name: "cadvisor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]

  # NGINX Proxy via Exporter
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]
