worker_processes auto;

events {
    worker_connections 1024;
}

http {

    upstream blue_backend {
        server server_blue:5000;
    }

    upstream green_backend {
        server server_green:5000;
    }

    # Default backend is blue
    map $http_x_deploy_target $active_backend {
        default blue_backend;
        green   green_backend;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$active_backend;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
