apiVersion: 1
datasources:
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    uid: azure-monitor
    isDefault: false
    jsonData:
      azureAuthType: clientsecret
      tenantId: ${arm_tenant_id}
      clientId: ${arm_client_id}
      subscriptionId: ${arm_subscription_id}
    secureJsonData:
      clientSecret: ${arm_client_secret}
